# Generated by Django 5.2.9 on 2025-12-15 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_workout_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_streaks',
            },
        ),
        migrations.CreateModel(
            name='WorkoutHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='workouts.programday')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='workouts.workoutprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Workout histories',
                'db_table': 'workout_history',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=True)),
                ('actual_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_reps', models.CharField(blank=True, max_length=50)),
                ('weight_used', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='workouts.exercise')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_completions', to='progress.workouthistory')),
            ],
            options={
                'db_table': 'exercise_completions',
            },
        ),
    ]
