# Generated by Django 5.2.9 on 2025-12-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
