# Generated by Django 5.2.9 on 2025-12-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutprogram_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
